---

- name: Ensure lvm2 is not present.
  pacman:
    name: lvm2
    state: absent


# If lvm2 sneaks onto our machine (via something that requires it as a
# dependency, e.g. udisks) then several services will be enabled automatically.
- name: Mask lvm services.
  systemd:
    name: "{{ item }}"
    masked: yes
  with_items:
    - lvm2-metad.socket
    - lvm2-lvmpolld.socket
    - lvm2-monitor.service

# genfstab supplies the subvol= and subvolid= mount options.
# These are set to  btrfs_root_subvolume.
# We instead want to delegate to the current default subvolume, so that snapper
# rollback setting the default actually boots us into a different subvolume.
# TODO: Make this more robust; this is only guaranteed by looking at the generated /etc/fstab.
- name: Remove subvol entry in root fstab to allow default subvolume to be mounted.
  replace:
    path: /etc/fstab
    regexp: "(.*),subvolid=.*,subvol=/{{ btrfs_root_subvolume }},subvol={{ btrfs_root_subvolume }}(.*)"
    replace: '\1\2'

- name: Install snapper to manage btrfs snapshots.
  pacman:
    name: snapper

- name: Create root snapper configuration.
  command: snapper -c root create-config /
  args:
    creates: /etc/snapper/configs/root

- name: Mount root snapshot subvolume at boot.
  mount:
    fstype: btrfs
    path: /.snapshots
    opts: "subvol={{ btrfs_root_subvolume }}/.snapshots"
    src: "{{ btrfs_root_device }}"
    state: mounted

- name: Install snap-pac for automatic snapshots.
  pacman:
    name: snap-pac
