---

# If lvm2 sneaks onto our machine (via something that requires it as a
# dependency, e.g. udisks) then several services will be enabled automatically.
# If we're using btrfs, however, we have no need for lvm2.
- name: Mask lvm services.
  systemd:
    name: "{{ item }}"
    masked: yes
  with_items:
    - lvm2-lvmetad.socket
    - lvm2-lvmpolld.socket
    - lvm2-monitor.service

- name: Ensure btrfs utilities are installed.
  pacman:
    name: btrfs-progs

# genfstab supplies the subvol= and subvolid= mount options.
# These are set to  btrfs_root_subvolume.
# We instead want to delegate to the current default subvolume, so that snapper
# rollback (which sets the default subvolume) actually boots us into a different subvolume.
# TODO: Make this more robust; this is only guaranteed by looking at the generated /etc/fstab.
- name: Remove subvol entry in root fstab to allow default subvolume to be mounted.
  replace:
    path: /etc/fstab
    regexp: "(.*),subvolid=.*,subvol=/{{ btrfs_root_subvolume }},subvol={{ btrfs_root_subvolume }}(.*)"
    replace: '\1\2'

- name: Create /home/{{ user_name }}/.cache directory if not already present.
  file:
    path: /home/{{ user_name }}/.cache
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
    state: directory

# We convert /home so that we can snapshot it by itself,
# And the cache folders so they can be excluded from snapshotting.
- include_tasks: convert-subvolume.yml
  loop:
    - /home/{{ user_name }}
    - /home/{{ user_name }}/.cache
    - /var/cache
  loop_control:
    loop_var: directory

- name: Set permissions of /home/{{ user_name }}
  file:
    path: /home/{{ user_name }}
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0700'
    state: directory

- name: Set permissions of /home/{{ user_name }}/.cache
  file:
    path: /home/{{ user_name }}/.cache
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0755'
    state: directory

# If we rollback even once then our default subvolume changes to a snapshot.
# This means that the root subvolume won't be mounted by default, and with it
# its direct child subvolumes. Thus, we explicitly mount them.
# However, we do not mount the grandchildren modules like /home/{{ user_name }}/.cache;
# we cannot rollback non-root subvolumes, so if we mount the direct children,
# the grandchildren are guaranteed to be mounted properly.
- name: Mount {{ item }} subvolume at boot.
  mount:
    fstype: btrfs
    path: "{{ item }}"
    opts: "subvol={{ btrfs_root_subvolume }}{{ item }}"
    src: "{{ btrfs_root_device }}"
    state: present
  with_items:
    - /home/{{ user_name }}
    - /var/cache
