---

- name: Ensure lvm2 is not present.
  pacman:
    name: lvm2
    state: absent


# If lvm2 sneaks onto our machine (via something that requires it as a
# dependency, e.g. udisks) then several services will be enabled automatically.
- name: Mask lvm services.
  systemd:
    name: "{{ item }}"
    masked: yes
  with_items:
    - lvm2-metad.socket
    - lvm2-lvmpolld.socket
    - lvm2-monitor.service
