---

- name: Install ATI package
  pacman:
    name: xf86-video-ati
  become: yes

- name: Add 'radeon' module to /etc/mkinitcpio.conf
  lineinfile:
    dest: /etc/mkinitcpio.conf
    backrefs: yes
    regexp: '^MODULES="(((?!radeon).)*)"$'
    line: 'MODULES="\1 radeon"'
  notify:
    - Create initial ramdisk environment
