---

- name: Install ATI package
  pacman:
    name: xf86-video-ati
  become: yes

- name: Add 'radeon' module to /etc/mkinitcpio.conf
  lineinfile:
    dest: /etc/mkinitcpio.conf
    insertafter: '^MODULES.*'
    line: 'MODULES+=" radeon"'
  notify:
    - Create initial ramdisk environment
