---

- name: Install makepkg dependencies
  pacman:
    name: "{{ item }}"
  with_items:
    - binutils # for the 'strip' binary
    - ccache
    - fakeroot # So that we may enter the 'fakeroot' environment to build aura

- name: Check if Aura is installed.
  command: pacman -Qi aura
  register: aura_installed
  ignore_errors: yes
  # We're only reading the state of the machine, so this never changes anything.
  changed_when: False
  # Have this run even when in check-mode as subsequent tasks depend on 'aura_installed' being set.
  check_mode: no

- name: Install sudo to change to 'nobody'
  pacman:
    name: sudo

- name: Download and extract aura
  unarchive:
    src: "https://aur.archlinux.org/cgit/aur.git/snapshot/aura-bin.tar.gz"
    dest: /tmp
    copy: no
  become: yes
  become_user: nobody
  when: aura_installed|failed

- name: Prepare aura installation
  command: makepkg --noconfirm
  args:
    chdir: /tmp/aura-bin
  become: yes
  become_user: nobody
  when: aura_installed|failed

- name: Install aura
  shell: pacman --upgrade aura-bin-*-x86_64.pkg.tar.xz --noconfirm
  args:
    chdir: /tmp/aura-bin
  become: yes
  when: aura_installed|failed
