---

# Install AUR helper
# Hopefully ansible will support this out of the box.
# I mean, this will fall over at the slightest breeze.

# Execute non-user things as 'nobody' or as ansible_ssh_user
# Then we could shift this into 'system'
# Or just create a temporary user and delete it after installing aura

- name: Install ccache for makepkg
  pacman:
    name: ccache
  become: yes

- name: Check if Aura is installed.
  command: pacman -Qi aura
  register: aura_installed
  ignore_errors: yes
  # We're only reading the state of the machine, so this never changes anything.
  changed_when: False
  # Have this run even when in check-mode as subsequent tasks depend on 'aura_installed' being set.
  check_mode: no

- name: Download and extract aura
  unarchive:
    src: "https://aur.archlinux.org/cgit/aur.git/snapshot/aura-bin.tar.gz"
    dest: /tmp
    copy: no
  become: yes
  become_user: nobody
  when: aura_installed|failed

- name: Install aura dependencies
  pacman:
    name: abs
  become: yes

- name: Prepare aura installation
  command: makepkg --noconfirm
  args:
    chdir: /tmp/aura-bin
  become: yes
  become_user: nobody
  when: aura_installed|failed

- name: Install aura
  command: pacman -U aura-bin-1.3.8-1-x86_64.pkg.tar.xz --noconfirm
  args:
    chdir: /tmp/aura-bin
  become: yes
  when: aura_installed|failed
