---

- name: Install Chromium web browser
  pacman:
    name:
      - chromium
      # Dependencies
      - profile-sync-daemon

- name: Install Chromium extensions
  aura:
    name: chromium-widevine # For Netflix

- name: Use psd-overlay-helper
  lineinfile:
    dest: /etc/sudoers
    line: "{{ user_name }} ALL=NOPASSWD: /usr/bin/psd-overlay-helper"
    validate: visudo -cf %s
