---

- name: Install cups.
  pacman:
    name: cups

- name: Create '{{ cups_admin_group }}' group.
  group:
    name: '{{ cups_admin_group }}'

# We do not add ourselves to the 'cups' group for security reasons.
- name: Add '{{ user_name }}' to '{{ cups_admin_group }}' group.
  user:
    name: '{{ user_name }}'
    groups:
      - "{{ cups_admin_group }}"
    append: yes

- name: Enable the cups service at boot.
  systemd:
    name: org.cups.cupsd
    state: started
    enabled: yes
  tags:
    - notest

- name: Set default paper size to {{ cups_paper_size }}.
  template:
    src: papersize.j2
    dest: /etc/papersize

- name: Allow users in 'cups' group to administrate printers
  lineinfile:
    dest: /etc/cups/cups-files.conf
    regexp: '^SystemGroup'
    # sys and root are already in there default.
    # We do not append 'cups' for security reasons, so we make our custom group
    line: SystemGroup sys root {{ cups_admin_group }}
  notify:
    - Restart cups

- name: Install AUR printer drivers
  aura:
    name: "{{ cups_aur_printer_drivers }}"
