---
- hosts: localhost
  become: yes
  roles:
    - aura
    - autologin
    - bspwm
    - chromium
    - development
    - desktop
    - docker
    - dotfiles
    - retroarch
    - system
    - user
    - vim_plugins
    - xorg
  vars:
    system_hostname: docker
