---
- hosts: localhost
  become: yes
  roles:
    - aura
    # We rely on subvolumes in the btrfs role, which we can't rely on on a foreign system that has docker
    # (it could be using a different driver)
    # - btrfs
    - autologin
    - bspwm
    - chromium
    - development
    - desktop
    - docker
    - dotfiles
    - retroarch
    - system
    - user
    - vim_plugins
    - xorg
  vars:
    system_hostname: docker
