---
- hosts: localhost
  become: yes
  roles:
    - aura
    - btrfs
    - autologin
    - bspwm
    - chromium
    - development
    - desktop
    - docker
    - dotfiles
    - retroarch
    - system
    - user
    - vim_plugins
    - xorg
  vars:
    system_hostname: docker
    # Snapper will bail if we try to create a config for an invalid volume.
    btrfs_snapper_configurations: []
