---
- hosts: localhost
  become: yes
  roles:
    - aura
    - autologin
    - bspwm
    - btrfs
    - chromium
    - development
    - desktop
    - docker
    - dotfiles
    - intel
    - java_development
    - laptop
    - radeon
    - snapper
    - system
    - systemd-boot
    - thinkpad
    - user
    - vim_plugins
    - xorg
  vars:
    system_hostname: flygon
    systemd_boot_device: /dev/sda3
