---

# Install and deploy dotfiles

- name: Install git to download dotfiles
  package:
    name: git
  become: yes

- name: Install stow to bootstrap dotfiles
  package:
    name: stow
  become: yes

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles.repository }}"
    dest: /home/{{ user.name }}/.dotfiles
    depth: 1
    recursive: yes
    update: no # We tend to tinker with dotfiles a bit.
    version: master
  become: yes
  become_user: "{{ user.name }}"

- name: Install dotfiles
  command: "{{ dotfiles.install }}"
  args:
    chdir: /home/{{ user.name }}/.dotfiles
    # We just pick a file that we know will always be installed, and use that as our check.
    creates: /home/{{ user.name }}/.config/nvim/init.vim
  become: yes
  become_user: "{{ user.name }}"
