---

- name: Create user {{ user.name }} in wheel group
  user:
    name: "{{ user.name }}"
    groups: wheel
    password: "{{ user.password }}"
    update_password: on_create
    createhome: yes
  become: yes

- name: Install preferred shell for {{ user.name }}
  package:
    name: "{{ user.shell }}"
    state: present
  become: yes

- name: Set preferred shell for {{ user.name }}
  user:
    name: "{{ user.name }}"
    shell: /usr/bin/{{ user.shell }}
  become: yes

- name: Create "Code" folder
  file:
    path: /home/{{ user.name }}/Code
    state: directory
  become: yes
  become_user: "{{ user.name }}"
