---

- name: Create user {{ username }} in wheel group
  user: name={{ username }}
        groups=wheel
        password="{{ user_password }}"
        createhome=yes
  become: yes

# TODO: set shell in a var
- name: Install preferred shell for {{ username }}
  package: name={{ user_shell }}
           state=present
  become: yes

- name: Set preferred shell for {{ username }}
  user: name={{ username }}
        shell=/usr/bin/{{ user_shell }}
  become: yes