---

- include: xorg.yml
- include: fonts.yml
- include: media.yml

- name: Install GTK themes
  pacman:
    name: "{{ item }}"
  with_items:
    - gtk-engine-murrine
    - gtk-engines
    - numix-gtk-theme
    - arc-gtk-theme

- name: Install GTK themes (AUR)
  aura:
    name: "{{ item }}"
    delmakedeps: yes
  with_items:
    - gtk-theme-numix-solarized
    - paper-gtk-theme-git
    - paper-icon-theme-git
    - numix-icon-theme-git
    - gtk-theme-solarc-git

- name: Install notifier
  pacman:
    name: {{ item }}
  with_items:
    - dunst
    - notification-daemon

- name: Install redshift
  pacman:
    name: redshift
