---

- name: Install fonts
  pacman:
    name:
      - noto-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-font-awesome
      - ttf-hack
      - ttf-liberation
      - ttf-roboto
      - ttf-ubuntu-font-family

- name: Install fonts (AUR)
  aura:
    name:
      - gohufont
      - ttf-mac-fonts
      - ttf-ms-fonts
      - ttf-roboto-mono
      - ttf-vista-fonts
      - siji-git
    delmakedeps: yes

# Need 32-bit libraries :(
# - name: Install steam
#   pacman: name=steam
#   become: yes

- name: Install mpv video player
  pacman:
    name: mpv

- name: Install zathura reader with extensions
  pacman:
    name:
      - zathura
      - zathura-cb
      - zathura-djvu
      - zathura-pdf-mupdf
      - zathura-ps

- name: Install GTK themes
  pacman:
    name:
      - gtk-engine-murrine
      - gtk-engines
      - arc-gtk-theme

- name: Install GTK themes (AUR)
  aura:
    name:
      - gtk-theme-numix-solarized
      - numix-icon-theme-git
      - gtk-theme-solarc-git
    delmakedeps: yes

- name: Install notifier
  pacman:
    name:
      - dunst
      - notification-daemon

- name: Install redshift
  pacman:
    name: redshift
