---

- include: xorg.yml
- include: fonts.yml
- include: media.yml
- include: themes.yml

- name: Install notifier
  pacman: name={{ item }}
  with_items:
    - dunst
    - notification-daemon
  become: yes

- name: Install redshift
  pacman: name=redshift
  become: yes
