---

- name: Install window manager
  pacman:
    name: "{{ item }}"
  with_items:
    - bspwm
    - sxhkd
  become: yes

- name: Install window manager utilities
  pacman:
    name: "{{ item }}"
  with_items:
    - rofi
    - i3lock
    - unclutter
    - feh
    - scrot
    - graphicsmagick
  become: yes

- name: Install window manager utilities (AUR)
  aura:
    name: "{{ item }}"
    delmakedeps: yes
  with_items:
    - lemonbar-git
  become: yes

# TODO: Make PKGBUILD for lightstatus

- name: Install lighstatus dependencies
  pacman:
    name: "{{ item }}"
  with_items:
    - alsa-lib
    - libevdev
    - wireless_tools
  become: yes

- name: Download lightstatus
  git:
    repo: "https://github.com/AlexandreCarlton/lightstatus.git"
    dest: /tmp/lightstatus
    version: master
  become: yes
  become_user: nobody

- name: Make lightstatus
  make:
    chdir: /tmp/lightstatus
  become: yes
  become_user: nobody

- name: Install lightstatus
  make:
    chdir: /tmp/lightstatus
    target: install
  become: yes
