---

- name: Install window manager
  pacman:
    name: "{{ item }}"
  with_items:
    - bspwm
    - sxhkd
  become: yes

- name: Install window manager utilities
  pacman:
    name: "{{ item }}"
  with_items:
    - rofi
    - i3lock
    - unclutter
    - feh
    - scrot
    - graphicsmagick
  become: yes

- name: Install window manager utilities (AUR)
  aura:
    name: "{{ item }}"
    delmakedeps: yes
  with_items:
    - lemonbar-git
  become: yes

# TODO: Make PKGBUILD for lightstatus

- name: Install lighstatus dependencies
  pacman:
    name: "{{ item }}"
  with_items:
    - alsa-lib
    - libevdev
    - wireless_tools
  become: yes

- name: Download lightstatus
  git: repo=https://github.com/AlexandreCarlton/lightstatus.git
       dest=/home/{{ user.name }}/Code/lightstatus
  become: yes
  become_user: "{{ user.name }}"

- name: Make lightstatus
  make: chdir=/home/{{ user.name }}/Code/lightstatus
  become: yes
  become_user: "{{ user.name }}"

- name: Install lightstatus
  make: chdir=/home/{{ user.name }}/Code/lightstatus target=install
  become: yes
