---
# Just install everything with xorg for now
# Later we can discover what we actually need
- name: Install xorg
  pacman:
    name:
      - xorg
      - xorg-apps
      - xorg-server
      # If xorg can't find the specific driver for our hardware, it defaults to fbdev.
      - xf86-video-fbdev

# Had to manually rewrite this; could be a line-ending thing.
- name: Allow Xorg to be used by anyone
  copy:
    src: Xwrapper.config
    dest: /etc/X11/Xwrapper.config

- name: Set default display
  lineinfile:
    dest: /etc/systemd/user.conf
    state: present
    line: "DefaultEnvironment=DISPLAY=:0"
