---
- name: Install retroarch
  pacman:
    name: retroarch

- name: Install retroarch cores
  pacman:
    name: libretro-{{ item }}
  with_items: "{{ retroarch_cores }}"

- name: Install retroarch utilities
  pacman:
    name: "{{ item }}"
  with_items:
    - retroarch-assets-xmb

- name: Install AUR retroarch utilities
  aura:
    name: "{{ item }}"
  with_items:
    - retroarch-autoconfig-udev-git # automatically map joypad buttons when plugged in.
