---

# This conflicts with the proprietary NVIDIA driver
- name: Remove opensource nouveau driver.
  pacman:
    name: xf86-video-nouveau
    state: absent

- name: Install nvidia drivers.
  pacman:
    name:
      - nvidia
      - nvidia-utils

- name: Install prime package for dynamic switching.
  pacman:
    name: nvidia-prime
