---

# This conflicts with the proprietary NVIDIA driver and the module itself will
# be blocklisted; eagerly purge it in the interests of space-saving.
- name: Remove opensource nouveau driver.
  pacman:
    name: xf86-video-nouveau
    state: absent

- name: Install nvidia drivers.
  pacman:
    name:
      - nvidia
      - nvidia-utils

- name: Install prime package for dynamic switching.
  pacman:
    name: nvidia-prime
