---

# Install and deploy dotfiles

- name: Install packages to download and deploy dotfiles
  package:
    name:
      - git
      - make
      - stow

- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: /home/{{ user_name }}/.dotfiles
    recursive: yes
    update: no # We tend to tinker with dotfiles a bit.
    version: master
  become: yes
  become_user: "{{ user_name }}"

- name: Install dotfiles
  command: "{{ dotfiles_install_cmd }}"
  args:
    chdir: /home/{{ user_name }}/.dotfiles
    # We just pick a file that we know will always be installed, and use that as our check.
    creates: /home/{{ user_name }}/.config/nvim/init.lua
  become: yes
  become_user: "{{ user_name }}"
