---
- name: Install bspwm and sxhkd
  pacman:
    name:
      - bspwm
      - sxhkd

- name: Install bspwm utilities
  pacman:
    name:
      - rofi
      - i3lock
      - unclutter
      - feh
      - scrot
      - graphicsmagick
      - polybar
