---
- name: Install bspwm and sxhkd
  pacman:
    name:
      - bspwm
      - sxhkd

- name: Install bspwm utilities
  pacman:
    name:
      - rofi
      - i3lock
      - unclutter
      - feh
      - scrot
      - graphicsmagick
      - pacman-contrib

- name: Install window manager utilities (AUR)
  aura:
    name:
      - lemonbar-git
    delmakedeps: yes

# TODO: Make PKGBUILD for lightstatus
- name: Install lightstatus build dependencies
  pacman:
    name:
      - clang
      - make

- name: Install lighstatus runtime dependencies
  pacman:
    name:
      - alsa-lib
      - libevdev
      - wireless_tools

- name: Download lightstatus
  git:
    repo: "https://github.com/AlexandreCarlton/lightstatus.git"
    dest: /tmp/lightstatus
    version: master
  become: yes
  become_user: nobody

- name: Make lightstatus
  make:
    chdir: /tmp/lightstatus
  become: yes
  become_user: nobody

- name: Install lightstatus
  make:
    chdir: /tmp/lightstatus
    target: install
