---
- name: Install bspwm and sxhkd
  pacman:
    name: "{{ item }}"
  with_items:
    - bspwm
    - sxhkd

- name: Install bspwm utilities
  pacman:
    name: "{{ item }}"
  with_items:
    - rofi
    - i3lock
    - unclutter
    - feh
    - scrot
    - graphicsmagick

- name: Install window manager utilities (AUR)
  aura:
    name: "{{ item }}"
    delmakedeps: yes
  with_items:
    - lemonbar-git

# TODO: Make PKGBUILD for lightstatus
- name: Install lightstatus build dependencies
  pacman:
    name: "{{ item }}"
  with_items:
    - gcc
    - make

- name: Install lighstatus runtime dependencies
  pacman:
    name: "{{ item }}"
  with_items:
    - alsa-lib
    - libevdev
    - wireless_tools

- name: Download lightstatus
  git:
    repo: "https://github.com/AlexandreCarlton/lightstatus.git"
    dest: /tmp/lightstatus
    version: master
  become: yes
  become_user: nobody

- name: Make lightstatus
  make:
    chdir: /tmp/lightstatus
  become: yes
  become_user: nobody

- name: Install lightstatus
  make:
    chdir: /tmp/lightstatus
    target: install
