---
- name: Install bspwm and sxhkd
  pacman:
    name:
      - bspwm
      - sxhkd

- name: Install bspwm utilities
  pacman:
    name:
      - rofi
      - unclutter
      - feh
      - scrot
      - graphicsmagick

- name: Install bspwm utilities (AUR)
  aura:
    name:
      - polybar
      - i3lock-fancy-rapid-git
