---

# Tasks to install vim plugins
# Easier to track than calling vim +PlugInstall
# If we miss a couple of plugins, vim-plug will catch them anyway.

- name: Force creation of Vim-Plug folder
  file:
    path: /home/{{ user_name }}/.config/nvim/autoload
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory

- name: Install Vim-Plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: /home/{{ user_name }}/.config/nvim/autoload/plug.vim
  become: yes
  become_user: "{{ user_name }}"

- name: Install Vim Plugins
  command: vim +PlugInstall +qall
