---

# Installing dash gives a slight speed up.

- name: Install dash shell
  pacman: name=dash
  become: yes

- name: Set /bin/sh to point to dash
  file:
    path: /bin/sh
    src: dash
    state: link
    force: yes
  become: yes
