---

# Before we dive into other roles, update the distro to guarantee current packages
- name: Update Arch Linux cache
  pacman:
    update_cache: yes
  # Older versions of ansible seem to always set this to 'true', ruining idempotency
  # Technically this _isn't_ idempotent, but for practical purposes it is.
  changed_when: false

- name: Give wheel group sudo (with password) privileges
  lineinfile:
    dest: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Install hostname
  pacman:
    name: inetutils

- name: Set hostname to {{ system_hostname }}
  hostname:
    name: "{{ system_hostname }}"
  # hostnamectl doesn't work properly in a container (which is used for testing)
  # See https://lists.freedesktop.org/archives/systemd-devel/2017-February/038291.html
  tags:
    - notest

- name: Set timezone to {{ system_timezone }}
  timezone:
    name: "{{ system_timezone }}"
  tags:
    - notest

- name: Sync date/time with network
  systemd:
    name: systemd-timesyncd
    enabled: yes
  tags:
    - notest

- name: Set locale to {{ system_locale }}
  locale_gen:
    name: "{{ system_locale }}"

# Installing dash gives a slight speed up.
- name: Install dash shell
  pacman:
    name: dash

# Bash upgrades reset /bin/sh
- name: Add hook to repoint /bin/sh to dash on upgrade
  aura:
    name: dashbinsh

- name: Set /bin/sh to point to dash
  file:
    path: /bin/sh
    src: dash
    state: link
    force: yes

- name: Install linux-zen kernel
  pacman:
    name:
      - linux-zen
      - linux-zen-headers

- name: Install mkinitcpio and presets
  pacman:
    name:
      - linux
      - mkinitcpio

- name: Install mkinitcpio configuration
  copy:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
  notify:
    - Create initial ramdisk environment

- name: Install pacman.conf
  copy:
    src: etc/pacman.conf
    dest: /etc/pacman.conf

- name: Install sound infrastructure & utilities
  pacman:
    name:
      - alsa-utils
      - pipewire
      - pipewire-alsa
      - pipewire-pulse

- name: Install openssh
  pacman:
    name: openssh

- name: Install firmare
  pacman:
    name: linux-firmware

- name: Enable Out-Of-Memory (OOM) Killer
  systemd:
    name: systemd-oomd
    started: yes
    enabled: yes
  tags:
    - notest

- name: Enable paccache
  systemd:
    name: paccache.timer
    started: yes
    enabled: yes
  tags:
    - notest

# This is useful to retroactively understand what happened to the system after
# it experiences unusual behaviour.
- name: Install system monitor
  pacman:
    name: sysstat

- name: Create override directory for system monitoring
  file:
    path: /etc/systemd/system/sysstat-collect.timer.d
    state: directory

- name: Run system monitoring every minute
  copy:
    src: sysstat-collect-timer-override.conf
    dest: /etc/systemd/system/sysstat-collect.timer.d/override.conf
  notify:
    - Restart system monitoring

- name: Enable system monitoring
  systemd:
    name: sysstat.service
    started: yes
    # This will enable a timer to collect stats and generate a report.
    enabled: yes
  tags:
    - notest
