---

# TODO: Add mirrorlist, then update (unless below does that for us)

# Before we dive into other roles, update the distro to guarantee current packages
- name: Upgrade Arch Linux
  pacman:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Give wheel group sudo (with password) privileges
  lineinfile:
    dest: /etc/sudoers  
    line: "%wheel ALL=(ALL) ALL"
    state: present
    validate: 'visudo -cf %s'
  become: yes

- name: Set hostname to {{ system.hostname }}
  hostname: name={{ system.hostname }}
  become: yes

- include: dash.yml
