---

# TODO: Make this a separate role, adjusts the systemd-boot entry as well.
- name: Install intel microcode updates
  pacman:
    name: intel-ucode

- name: Create /boot/loader
  file:
    path: /boot/loader
    state: directory

- name: Copy in loader.conf
  copy:
    src: loader.conf
    dest: /boot/loader/loader.conf

- name: Copy in Arch Linux entry
  template:
    src: arch.conf.j2
    dest: /boot/loader/entries/arch.conf

- name: Copy in Arch Linux variant entries
  template:
    src: arch-variant.conf.j2
    dest: /boot/loader/entries/arch-{{ item }}.conf
  with_items:
    - zen
