---

- name: Install Java 8
  pacman:
    name: jdk8-openjdk

- name: Install common Java build tools
  aura:
    name:
      - bazelisk-bin

# The community-supported version lags a bit behind the latest release.
- name: Install IntelliJ Community Edition
  aura:
    name: intellij-idea-ce
  when: not has_jetbrains_licence

- name: Install IntelliJ Ultimate Edition
  aura:
    name: intellij-idea-ultimate-edition
  when: has_jetbrains_licence

# See https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Set inotify watches limit to {{ inotify_max_user_watches }}
  lineinfile:
    path: /etc/sysctl.d/idea.conf
    regexp: "^fs.inotify.max_user_watches.*"
    line: "fs.inotify.max_user_watches = {{ inotify_max_user_watches }}"
    create: yes
