---

# TODO: Add xf86 graphics
# Will need to adjust based on laptop model.

# We use networkmanager for the following reasons:
# - It is maintained by RedHat
# - It is popular (and thus problems are google-able)
# - It manages wired/wireless connection transitions seamlessly.
#
- name: Install networking services
  pacman:
    name:
      - networkmanager
      - networkmanager-openconnect # VPN
      - iwd # wireless backend (replaces wpa_supplicant)

- name: Enable iwd backend for networkmanager
  copy:
    src: wifi_backend.conf
    dest: /etc/NetworkManager/conf.d/wifi_backend.conf

# We should only have one networking service (NetworkManager) enabled.
# Not we don't start/stop so as not to interrupt Ansible.
- name: Ensure other networking services are disabled.
  systemd:
    name: "{{ item }}"
    enabled: no
  tags:
    - notest
  loop:
    - systemd-networkd.service
    - systemd-networkd.socket
    # NetworkManager starts and manages iwd itself, so we shouldn't enable it here.
    - iwd.service
    # We want to use iwd instead of this.
    - wpa_supplicant.service

- name: Enable network services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  tags:
    - notest
  loop:
    # This is installed with systemd.
    - systemd-resolved
    - networkmanager

# This forces NetworkManager to use systemd-resolved.
# This is necessary for binaries not using nsswitch; e.g. go programs.
- name: Ensure /etc/resolv.conf points to systemd's stub
  file:
    path: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

# If something messes up with networkd/iwd,
# we should have some extra packages to try
- name: Install fallback network managers and backends
  pacman:
    name:
      - connman
      - networkmanager
      - wpa_supplicant

- name: Install battery / thermal reader
  pacman:
    name: acpi

- name: Install thermald
  aura:
    name: thermald

- name: Enable thermald
  service:
    name: thermald
    enabled: yes

- name: Install automounter (AUR)
  aura:
    name: ldm
    delmakedeps: yes

- name: Enable automounter
  systemd:
    name: ldm
    state: started
    enabled: yes
  tags:
    - notest

- name: Install automounter configuration
  template:
    src: ldm.conf.j2
    dest: /etc/ldm.conf

- name: Install crda to use correct Wireless Regulatory Domain
  pacman:
    name: crda

- name: Set WRD to Australia
  lineinfile:
    dest: /etc/conf.d/wireless-regdom
    state: present
    regexp: '^#?WIRELESS_REGDOM="AU"'
    line: 'WIRELESS_REGDOM="AU"'
