---

# TODO: Add xf86 graphics
# Will need to adjust based on laptop model.

- name: Install connection manager
  pacman:
    name: "{{ item }}"
  with_items:
    - connman
    - wpa_supplicant
  become: yes

- name: Copy in connman configuration
  copy:
    src: etc/connman/main.conf
    dest: /etc/connman/main.conf
  become: yes

- name: Enable connman
  systemd:
    name: connman
    enabled: yes
  become: yes

- name: Install battery / thermal reader
  pacman:
    name: acpi
  become: yes

- name: Install thermald (AUR)
  aura:
    name: thermald-git
    delmakedeps: yes
  become: yes

- name: Enable thermald
  service:
    name: thermald
    enabled: yes
  become: yes

- name: Install automounter (AUR)
  aura:
    name: ldm
    delmakedeps: yes
  become: yes

- name: Enable automounter
  service:
    name: ldm
    enabled: yes
  become: yes

- name: Install automounter configuration
  template:
    src: ldm.conf.j2
    dest: /etc/ldm.conf
  become: yes