---

# TODO: Add xf86 graphics
# Will need to adjust based on laptop model.

- name: Install iwd
  pacman:
    name: iwd

- name: Setup wireless systemd network configuration
  copy:
    src: 25-wireless.network
    dest: /etc/systemd/network/25-wireless.network

- name: Enable network services
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  tags:
    - notest
  loop:
    - iwd
    # These are installed with systemd
    - systemd-networkd
    - systemd-resolved

# We are not using any extra network-managing tools that would modify /etc/resolv.conf,
# so we just point it to systemd's stub.
# This is necessary for binaries not using nsswitch; e.g. go programs.
- name: Ensure /etc/resolv.conf points to systemd's stub
  file:
    path: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link

# If something messes up with networkd/iwd,
# we should have some extra packages to try
- name: Install fallback network managers and backends
  pacman:
    name:
      - connman
      - networkmanager
      - wpa_supplicant

- name: Install battery / thermal reader
  pacman:
    name: acpi

- name: Install thermald
  aura:
    name: thermald

- name: Enable thermald
  service:
    name: thermald
    enabled: yes

- name: Install automounter (AUR)
  aura:
    name: ldm
    delmakedeps: yes

- name: Enable automounter
  systemd:
    name: ldm
    daemon_reload: yes
    enabled: yes
  tags:
    - notest

- name: Install automounter configuration
  template:
    src: ldm.conf.j2
    dest: /etc/ldm.conf

- name: Install crda to use correct Wireless Regulatory Domain
  pacman:
    name: crda

- name: Set WRD to Australia
  lineinfile:
    dest: /etc/conf.d/wireless-regdom
    state: present
    regexp: '^#?WIRELESS_REGDOM="AU"'
    line: 'WIRELESS_REGDOM="AU"'
