---

# TODO: Add xf86 graphics
# Will need to adjust based on laptop model.

- name: Install connection manager
  pacman:
    name:
      - connman
      - wpa_supplicant

- name: Create connman configuration folder
  file:
    path: /etc/connman
    state: directory

- name: Copy in connman configuration
  copy:
    src: etc/connman/main.conf
    dest: /etc/connman/main.conf

- name: Enable connman
  systemd:
    name: connman
    enabled: yes

# If something messes up with connman,
# we should have some extra packages to try
- name: Install fallback network managers
  pacman:
    name:
      - networkmanager
      - iwd

- name: Install battery / thermal reader
  pacman:
    name: acpi

- name: Install thermald
  aura:
    name: thermald

- name: Enable thermald
  service:
    name: thermald
    enabled: yes

- name: Install automounter (AUR)
  aura:
    name: ldm
    delmakedeps: yes

- name: Enable automounter
  systemd:
    name: ldm
    daemon_reload: yes
    enabled: yes

- name: Install automounter configuration
  template:
    src: ldm.conf.j2
    dest: /etc/ldm.conf

- name: Install crda to use correct Wireless Regulatory Domain
  pacman:
    name: crda

- name: Set WRD to Australia
  lineinfile:
    dest: /etc/conf.d/wireless-regdom
    state: present
    regexp: '^#?WIRELESS_REGDOM="AU"'
    line: 'WIRELESS_REGDOM="AU"'
