---
# This is the playbook run by molecule.
- name: Converge
  hosts: all
  pre_tasks:
    - name: Upgrade Arch Linux first
      pacman:
        update_cache: yes
        upgrade: yes
  roles:
    # Position reflector first to speed up downloads
    - reflector
    - aura
    - autologin
    - chromium
    - desktop
    - development
    - dotfiles
    - intel
    - java_development
    - laptop
    - neovim
    - optimus
    - sshd
    - sway
    - system
    - systemd-boot
    - user
    - yubikey
  vars:
    system_hostname: porygon
