---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: archlinux
    # Name of the image built from Dockerfile.j2
    image: alexandrecarlton/archlinux-molecule:latest
    privileged: true
    volumes:
      - molecule_pacman_cache:/var/cache/pacman
provisioner:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: 2
    ANSIBLE_LIBRARY: ../../modules/aura/library
verifier:
  name: ansible
