---
- name: Install main editors
  pacman:
    name: "{{ item }}"
  with_items:
    - gvim
    - neovim
    - emacs
  become: yes

- name: Install editor complements
  pacman:
    name: "{{ item }}"
  with_items:
    - ctags
    - cscope
    - python-neovim
    - python2-neovim
  become: yes

- name: Install editor complements (AUR)
  aura:
    name: "{{ item }}"
    delmakedeps: yes
  with_items:
    - editorconfig-core-c
  become: yes
