---
- name: Install main editors
  pacman: name={{ item }}
  with_items:
    - gvim
    - neovim
    - emacs
  become: yes

- name: Install editor complements
  pacman: name={{ item }}
  with_items:
    - ctags
    - cscope
    - python-neovim
    - python2-neovim
  become: yes

- name: Install EditorConfig (AUR)
  command: aura -A --delmakedeps --noconfirm editorconfig-core-c
  become: yes
