---

- name: Install Alacritty
  pacman:
    name:
      - alacritty

- name: Install fish + utilities
  pacman:
    name:
      - fish
      - fisher

- name: Install git + utilities
  pacman:
    name:
      - git
      - git-delta

- name: Install shell utilities
  pacman:
    name:
      - aspell
      - aspell-en
      - bat
      - exa
      - fd
      - fzf
      - htop
      - pass
      - ranger
      - ripgrep
      - shellcheck
      - tmux
      - wget
      - zoxide
