---
- name: Install VirtualBox Guest Additions
  pacman: name={{ item }}
  with_items:
    # Order seems to matter here (modules-arch before utils).
    - virtualbox-guest-modules-arch
    - virtualbox-guest-utils

# This loads the modules vbox{guest,sf,video}
# and syncs the guest time with that of the host's
- name: Enable vboxservice
  service:
    name: vboxservice
    enabled: yes

- name: Install VBoxClient services
  template:
    src: vboxclient.service.j2
    dest: /etc/systemd/user/vboxclient-{{ item }}.service
  with_items:
    - checkhostversion
    - clipboard
    - display
    - draganddrop
    - seamless

# We can't directly enable these services because there is no running systemd instance for {{ user_name }}

- name: Create default.target.wants
  file:
    name: /home/{{ user_name }}/.config/systemd/user/default.target.wants
    state: directory
  become: yes
  become_user: "{{ user_name }}"

- name: Enable VBoxClient services
  file:
    src: /etc/systemd/user/vboxclient-{{ item }}.service
    dest: /home/{{ user_name }}/.config/systemd/user/default.target.wants/vboxclient-{{ item }}.service
    state: link
  with_items:
    - checkhostversion
    - clipboard
    - display
    - draganddrop
    - seamless
  become: yes
  become_user: "{{ user_name }}"
