---

- name: Install yubikey utilities
  pacman:
    name:
      - ccid # for pcscd
      - libu2f-host # for chromium
      - yubikey-manager-qt

- name: Enable and start pcscd
  systemd:
    name: pcscd
    state: started
    enabled: yes
