---

- name: Install yubikey utilities
  pacman:
    name:
      - ccid # for pcscd
      - yubikey-manager-qt

# Note: if yubikey does not work with chromium, install libu2f-host

- name: Enable and start pcscd
  systemd:
    name: pcscd
    state: started
    enabled: yes
  tags:
    - notest
