---

# For some reason wlan is blocked, interfering with our wifi.
# We have to insert a systemd unit to automatically unblock it.

- name: Install rfkill
  pacman:
    name: rfkill
  become: yes

- name: Automatically unblock wlan on boot
  systemd:
    name: rfkill-unblock@wlan.service
    enabled: yes
    daemon_reload: yes
  become: yes