---

- name: Install rfkill to debug wireless issues if present
  pacman:
    name: rfkill
  become: yes

- name: Install ThinkPad packages
  pacman:
    name: '{{ item }}'
  with_items:
    - tp_smapi

- name: Add 'thinkpad_acpi' module to /etc/mkinitcpio.conf
  lineinfile:
    dest: /etc/mkinitcpio.conf
    backrefs: yes
    regexp: '^MODULES="(((?!thinkpad_acpi).)*)"$'
    line: 'MODULES="\1 thinkpad_acpi"'
  notify:
    - Create initial ramdisk environment
