---

- name: Install Docker
  pacman:
    name: docker

- name: Create 'docker' group if not already present
  group:
    name: docker
    # docker group is root-equivalent
    # Docker complains when it is not a system group
    system: yes

- name: Add '{{ user.name }}' to the 'docker' group
  user:
    name: '{{ user.name }}'
    groups:
      - docker
    append: yes

- name: Enable Docker socket on startup to start the daemon lazily
  systemd:
    name: docker.socket
    enabled: yes
    daemon_reload: yes
