---

# Install and enable fstrim to discard unused blocks on filesystem
- name: Install fstrim
  pacman:
    name: util-linux

- name: Enable fstrim timer
  systemd:
    name: fstrim.timer
    enabled: yes
