---

- name: Install snapper to manage btrfs snapshots.
  pacman:
    name: snapper

- name: Create root snapper configuration.
  command: snapper -c root create-config /
  args:
    creates: /etc/snapper/configs/root

- name: Create home_{{ user_name }} snapper configuration.
  command: snapper -c home_{{ user_name }} create-config /home/{{ user_name }}
  args:
    creates: /etc/snapper/configs/home_{{ user_name }}

# We won't rollback the subvolume (since we cannot set-default for a particular path, only /),
# so we only mount /home/<user> and not /home/<user>/.snapshots
- name: Allow user {{ user_name }} to manage home_{{ user_name }} snapper configuration.
  lineinfile:
    path: /etc/snapper/configs/home_{{ user_name }}
    regexp: '^ALLOW_USERS='
    line: 'ALLOW_USERS="{{ user_name }}"'

# Clean up snapshots since we'll just keep consuming space.
# See https://www.suse.com/documentation/sles-12/book_sle_admin/data/sec_snapper_clean-up.html for configuration details.

- name: Enable number cleanup algorithm for each configuration.
  lineinfile:
    path: /etc/snapper/configs/{{ item }}
    regexp: '^NUMBER_CLEANUP='
    line: 'NUMBER_CLEANUP="yes"'
  with_items:
    - root
    - home_{{ user_name }}

- name: Disable age as a criteria to satisfy before automatically removing snapshots for each configuration.
  lineinfile:
    path: /etc/snapper/configs/{{ item }}
    regexp: '^NUMBER_MIN_AGE='
    line: 'NUMBER_MIN_AGE=0'
  with_items:
    - root
    - home_{{ user_name }}

- name: Keep at most {{ snapper_number_limit }} snapshots for each configuration.
  lineinfile:
    path: /etc/snapper/configs/{{ item }}
    regexp: '^NUMBER_LIMIT='
    line: 'NUMBER_LIMIT={{ snapper_number_limit }}'
  with_items:
    - root
    - home_{{ user_name }}

- name: Enable snapper-cleanup to remove old snapshots.
  systemd:
    name: snapper-cleanup.timer
    state: started
    enabled: yes

# Normally pam_snapper is supposed to:
# - create a pre- and post- snapshot on login
# - create a pre- and post- snapshot on logout
# However, systemd-user is a bit weird since it doesn't trigger pam_snapper on logout, and pam_snapper never makes the post-snapshot.
# So we call 'openonly' to make a single snapshot on login.
- name: Enable pam_snapper in systemd-user to create snapshots of /home/{{ user_name }} on login.
  lineinfile:
    path: /etc/pam.d/systemd-user
    line: session  optional pam_snapper.so openonly

- name: Install snap-pac for automatic snapshots.
  pacman:
    name: snap-pac
