---
on:
  push:
    branches:
      - master
  schedule:
    - '0 0 * * 0'  # Midnight every Sunday
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
          submodules: 'true'
      - name: molecule
        uses: robertdebock/molecule-action@2.6.17
        env:
          PY_COLORS: '1' # Force Molecule to use colors
          ANSIBLE_FORCE_COLOR: '1' # Force Ansible to use colors
